apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-ingress-controller
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-ingress-controller
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    k8s-app: {{ .Release.Name }}-ingress-lb

spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}-ingress-lb
  template:
    metadata:
      annotations:
        k8s.aliyun.com/eci-instance-spec: "0.5-1.0Gi"
        k8s.aliyun.com/eci-instance-cpu: "0.5"
        k8s.aliyun.com/eci-instance-mem: "1.0"
      labels:
        k8s-app: {{ .Release.Name }}-ingress-lb
        name: {{ .Release.Name }}-ingress-lb
    spec:
      serviceAccountName: {{ .Release.Name }}-ingress-controller
      containers:
        - name: {{ .Release.Name }}
          image: traefik:v2.3.5
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --entryPoints.web.forwardedheaders.insecure=true
            - --log=true
            - --ping
            - --log.level=DEBUG
            - --log.format=json
            - --providers.kubernetescrd=true
            - --providers.kubernetesingress=true
            - --certificatesresolvers.{{ .Values.resolverName }}=true
            - --certificatesresolvers.{{ .Values.resolverName }}.acme.tlschallenge=true
            - --certificatesResolvers.{{ .Values.resolverName }}.acme.httpChallenge=true
            - --certificatesresolvers.{{ .Values.resolverName }}.acme.email={{ .Values.acme.email }}
            - --certificatesresolvers.{{ .Values.resolverName }}.acme.storage=acme.json
            - --certificatesresolvers.{{ .Values.resolverName }}.acme.dnschallenge.provider=route53
            - --certificatesresolvers.{{ .Values.resolverName }}.acme.dnschallenge.delaybeforecheck=0
            - --certificatesresolvers.{{ .Values.resolverName }}.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
            - --certificatesResolvers.{{ .Values.resolverName }}.acme.keyType={{ .Values.acme.keyType }}
            - --certificatesresolvers.{{ .Values.resolverName }}.acme.httpchallenge.entrypoint=web
            {{- if .Values.pilotToken }}
            - --pilot.token={{ .Values.pilotToken }}
            {{- end }}
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ingress-service
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: "internet"
spec:
  selector:
    k8s-app: {{ .Release.Name }}-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 443
      name: websecure
    - protocol: TCP
      port: 8080
      name: admin
  type: LoadBalancer