apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-temporary-redirect: "false"
spec:
  tls:
    options: {}
    certResolver: {{ .Values.resolverName }}
    domains:
      - main: {{ .Values.host }}
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.host }}`) && PathPrefix(`/{{ .Values.service.apiPrefix }}`)
  # - match: PathPrefix(`/{{ .Values.service.apiPrefix }}`)
    kind: Rule
    services:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      {{- if .Release.Namespace }}
      namespace: {{ .Release.Namespace }}
      {{- end }}
    middlewares:
      - name: {{ .Release.Name }}-prefix

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-addprefix
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  addPrefix:
    prefix: {{ .Values.path.prefix }}

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-stripprefix
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  stripPrefix:
    prefixes:
      - /{{ .Values.service.apiPrefix }}
      
---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-prefix
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  chain:
    middlewares:
    - name: {{ .Release.Name }}-stripprefix
    - name: {{ .Release.Name }}-addprefix
